import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "../components/navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-b from-black via-primary to-accent/50 min-h-screen'>
        <header className=' max-w-[1280px] mx-auto'>

          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
